apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-class-code
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-class-code
  template:
    metadata:
      labels:
        app: devops-class-code
    spec:
      containers:
        - name: c1
          image: 7720001490/myrepo:tomcatapp3
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-class-code
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: devops-class-code
